"""Collect demonstrations by running the scripted expert and logging what it commands.

The expert is the same IK + grasp stack the evaluation uses, so demonstrations are generated by a
controller whose behaviour is already measured — not by a separate teleoperation path that might
not match. Each frame pairs what the robot could *see* (wrist and scene cameras, joint state) with
what the expert *did* (the commanded joint targets), which is exactly the supervision an
imitation-learning policy needs.

Only successful episodes are kept by default. A failed grasp is still a valid trajectory to learn
from in principle, but mixing it in unlabelled teaches the policy to reproduce the failure.
"""

from __future__ import annotations

import numpy as np

from armanual.control.executor import Scheduler
from armanual.control import primitives as P
from armanual.control.grasp import grasp_from_detection
from armanual.perception.observer import CameraObserver
from armanual.policy.dataset import IMAGE_SIZE, EpisodeBuffer, Frame, goal_vector
from armanual.sim.randomize import RandomizationConfig, sample_scene
from armanual.sim.world import World


def _resize(image: np.ndarray, size=IMAGE_SIZE) -> np.ndarray:
    """Nearest-neighbour resize. Keeps the recorder dependency-free and is exactly what the
    policy sees at inference time, so training and deployment share one preprocessing path."""
    height, width = image.shape[:2]
    rows = (np.linspace(0, height - 1, size[1])).astype(np.int32)
    cols = (np.linspace(0, width - 1, size[0])).astype(np.int32)
    return image[rows][:, cols]


class DemoRecorder:
    """Runs one scripted pick-and-place per episode and records every control tick."""

    def __init__(self, world: World, observer: CameraObserver, arm: str, dt: float = 0.05):
        self.world = world
        self.observer = observer
        self.arm = arm
        self.dt = dt
        self.buffer: EpisodeBuffer | None = None
        self.goal = np.zeros(8, dtype=np.float32)
        self.phase = "approach"

    def capture(self, *_args) -> None:
        """Scheduler tick hook: log one frame."""
        if self.buffer is None:
            return
        handle = self.world.arms[self.arm]
        state = np.concatenate(
            [self.world.arm_qpos(self.arm)[:6], [self.world.gripper_opening(self.arm)]]
        ).astype(np.float32)[:7]
        action = np.array(self.world.data.ctrl[handle.actuator_ids], dtype=np.float32)
        self.buffer.add(
            Frame(
                wrist=_resize(self.world.render(f"{self.arm}/wrist_cam", (128, 128))),
                scene=_resize(self.world.render("cam_overhead", (128, 128))),
                state=state,
                goal=self.goal.copy(),
                action=action,
                phase=self.phase,
            )
        )


def record_pick_place(seed: int, *, arm: str | None = None, category: str = "cup",
                      randomization: RandomizationConfig | None = None,
                      place_offset=(0.0, 0.06)) -> EpisodeBuffer | None:
    """Record one pick-and-place demonstration; returns None when nothing suitable is in view."""
    scene = sample_scene(seed, randomization or RandomizationConfig.placement_only())
    world = World(scene)
    observer = CameraObserver(world)
    observation = observer.observe()

    candidates = [d for d in observation.detections if d.category == category]
    if not candidates:
        world.close()
        observer.close()
        return None
    detection = max(candidates, key=lambda d: d.pixel_area)

    if arm is None:
        arm = "right" if detection.position[0] >= 0 else "left"
    grasp = grasp_from_detection(detection, world.base_pos(arm)[:2],
                                 obj_yaw=float(detection.orientation))
    place_xy = (float(detection.position[0] + place_offset[0]),
                float(detection.position[1] + place_offset[1]))

    recorder = DemoRecorder(world, observer, arm)
    recorder.goal = goal_vector(
        detection.position, (place_xy[0], place_xy[1], 0.045),
        world.base_pos(arm)[:2], "approach",
    )
    buffer = EpisodeBuffer(seed=seed, task=f"pick_place_{category}", arm=arm)
    recorder.buffer = buffer

    scheduler = Scheduler(world, dt=0.05)
    scheduler.on_tick.append(recorder.capture)

    result = scheduler.run({arm: P.pick_detected(world, arm, grasp, attempts=1)}, max_seconds=40)
    if result.ok:
        recorder.phase = "place"
        recorder.goal = goal_vector(
            (place_xy[0], place_xy[1], 0.045), (place_xy[0], place_xy[1], 0.045),
            world.base_pos(arm)[:2], "place",
        )
        place = scheduler.run(
            {arm: P.place_held(world, arm, place_xy, height=0.045, jaw=grasp.jaw)},
            max_seconds=35,
        )
        buffer.success = place.ok
        buffer.notes = place.error or ""
    else:
        buffer.success = False
        buffer.notes = result.error or ""

    observer.close()
    world.close()
    return buffer
